vname: Download Artifact Workflow

on:
  workflow_dispatch:

jobs:
  download-artifact-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact-name 
        path: ~/harshaartifact  # Path to store the downloaded artifact in the home directory
