name: Download Artifact Workflow

on:
  workflow_dispatch:

jobs:
  download-artifact-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact-name  
        path: ~/harshaartifact 
