name: Input Integer Workflow

on:
  workflow_dispatch:
    inputs:
      first_integer:
        description: 'First Integer'
        required: true
        type: integer
      second_integer:
        description: 'Second Intger'
        required: true
        type: integer

jobs:
  sum-integers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sum the integers
      run: |
        # Get the inputs
        first_integer=${{ github.event.inputs.first_integer }}
        second_integer=${{ github.event.inputs.second_integer }}
        
        # Calculate the sum
        sum=$((first_integer + second_integer))
        
        # Print the result
        echo "The sum of $first_integer and $second_integer is: $sum"
