name: Hello harshavardhan

on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    environment: dev-harsha

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello harsvardhan"

  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying to production"
